#!/bin/bash
#PBS -N job-lu-44
#PBS -j oe
#PBS -l walltime=02:00:00,size=48
#PBS -A  CSC063


date

export MPICH_UNEX_BUFFER_SIZE=125829120
export MPICH_MAX_SHORT_MSG_SIZE=64000

ulimit -c 10000000

cd $PBS_O_WORKDIR

rm -f controlPointData.txt
rm -fr traces
mkdir traces

aprun -n 44 -N 11 ./lu-proj 32768 1000 30 +traceroot traces +gz-trace +setcpuaffinity +CPSaveData +CPGatherAll +CPMemoryAware +CPDefaultValues memory_threshold=1 +CPLoadData


