#!/bin/bash
#PBS -N lu-trace-100
#PBS -j oe
#PBS -l walltime=00:10:00,size=24
##PBS -A TG-ASC050039N
#PBS -A csc076

export MPICH_UNEX_BUFFER_SIZE=60M
export MPICH_MAX_SHORT_MSG_SIZE=1k
export MPICH_PTL_UNEX_EVENTS=60000

TRACES_DIR=jaguar100

cp ~liffland/charmlu/lu.trace $WORKDIR/lu.$TRACES_DIR
cd $WORKDIR

mkdir $TRACES_DIR
aprun -n 24 -N 12 ./lu.$TRACES_DIR 4000 500 1050 50 2 +setcpuaffinity +traceroot $TRACES_DIR +gz-trace +logsize 10000